### ISSUE TITLE
System Architecture Proposal

### ISSUE THREAD

**Issue by brebory** [jartis/accountabilibot#1]
# Accountabilibot Overview

Accountabilibot should be a platform built on three services:

1. Rest API
2. Web App
3. Discord Bot

The platform should offer three main features:

- The ability for users to form groups of accountabilibuddies of any size
- The ability for groups to create and track shared goals
- The ability for groups to schedule pairing sessions as a discord event

## Rest API

Manages the following models and their relationships:

- Users - Users can register with the Accountabilibot Discord Bot
  - Should be automatically created when the user interacts with the Discord bot
  - Essentially, the user's Discord ID so we can look them up via the Discord API when we need more user data
- Groups - Tracks which users are "buddied up", and should be tagged together
  - Users that share a group are buddied up
  - Users can have multiple groups of buddies
  - Groups can be associated with multiple Discord roles across guilds/servers
- Goals - Shared goals that buddies want to track together
  -  Two kinds: [Accomplishment, Habit]
  - Accomplishments have a subtable for completion dates
  - Habits are tracked via "checkins", which can be associated to multiple goals and multiple users, in case they worked together on a goal
- Checkins - Tracks which users worked on which goals together, and when
- Pairing Sessions - Schedules Discord events for buddies to work together
  - Could use calendar data for both buddies to suggest event times

### Data Store

I'm most comfortable working with a relational database but a nosql DB could work here as well. Definitely open for discussion.

### Tables

**`users`**

- `id` - [Snowflake](https://discord.com/developers/docs/reference#snowflakes)
  - Since we're focusing on Discord for now, the id for our users will also be the Discord id for the user 
  - I'm assuming we can pull whatever other info we want from the Discord User API, so we don't really need to store much else for users

**`groups`**

- `id` - ID Type
- `name` - String
- `description` - String

**`groupsxroles`**

- `id` - ID Type
- `guild-id` - [Snowflake](https://discord.com/developers/docs/reference#snowflakes)
- `role-id` - [Snowflake](https://discord.com/developers/docs/reference#snowflakes)
- `group-id` - ID Type
  - FK to `groups`, allows associating multiple roles across guilds w/ groups

**`usersxgroups`**

- `id` - ID Type
- `group-id` - ID Type
- `user-id` - [Snowflake](https://discord.com/developers/docs/reference#snowflakes)

**`goals`**

- `id` - ID Type
- `group-id` - ID Type
- `type` - Enum
  - `accomplishment`
  - `habit`
- `description` - String?

**`accomplishments`**

- `goal-id` - ID Type
- `when` - Epoch

**`checkins`**

- `id` - ID Type
- `when` - Epoch

**`checkinsxgoals`**

- `checkin-id` - ID Type
- `goal-id` - ID Type

**`usersxcheckins`**

- `user-id` - [Snowflake](https://discord.com/developers/docs/reference#snowflakes)
- `checkin-id` - ID Type

**`pairing-sessions`**

- `id` - ID Type
- `group-id` - ID Type
- `when` - Epoch
- `summary` - String
  - Will be used as the title of the created voice channel, if the bot should create an ad-hoc voice channel for the session
- `description` - String

## Web App

Handles Discord OAuth flow for user registration and offers a GUI for viewing and managing Users, Groups, Goals, Checkins, and Pairing Sessions.

Also offers a web admin interface for managing the Accountabilibot in Discord servers.

## Discord Bot

Offers a discord chat interface to the rest api, as an alternative to using the website to manage groups, goals and pairing sessions. Also, the bot can schedule events for pairing sessions, and create ad-hoc Voice channels to service those sessions.

**Comment by s-aring** [comment]
For goals - there are two types of goals. One is when you get something done by a particular date, and the other is when you are trying to establish a habit.  So the goal might be something like "lift weights three times a week" in which case a deadline doesn't make sense, some other data structure might.

**Comment by s-aring** [comment]
so maybe instead of a deadline, put a goal type, and if it's an accomplishment that can be a table with a goal id and a deadline, and if it's a habit, there can be a table with goal id, user id, group id, and check in time stamp. the web interface should be able to show check-ins in some easy-to-consume way.

**Comment by jartis** [comment]
> Also, the bot announces reminders to buddy groups in the configured channel.

Bots have the ability to manage a server - should this live in its own server, creating and tearing down voice channels with limited permissions as necessary? Invites can be sent via DM, and (I think) a user granting the permission can be auto-joined to channels at a scheduled time (cf., [sesh.fyi](https://sesh.fyi/))

**Comment by ericlevicky** [comment]
Discord utilizes epoch quite a bit, if you store the 'when' on a pairingsession as an epoch int I think it may save a lot of compute operations. `<t:{value}:R>` would print a relative time in discord.  You can also convert all discordids to an epoch which may be useful, say you have a messageid that you want to create an event 1 day from, you can pull the epoch from the snowflake and add 24 hours (https://discord.com/developers/docs/reference#snowflakes). 

Unless you're planning to support other user types besides discord, you're probably safe using the discordid of the user as the PK for the user table.  

If you're planning to leverage discord you can make roles and not have to store that info.  You can create a discord role and treat that as the group, then leverage existing discord apis (like discord.py) to get/maintain that kind of information. 
How many discord servers/guilds would you want this in?  If the answer is more than 1 and you want groups to cross guild boundaries then it would have to exist outside of a 'role' as the role would have different IDs based on the guild it's in.   

If you're using no-sql to store this data, then choosing the PKs is more important than in a relational database.  Ideally you'd want the pk to be what you're using to retrieve the record, if it's not you'd have to scan (with paging potentially) and a filter to select the data and that lacks in efficiency.

**Comment by brebory** [comment]
Nice @cartkid, thanks for linking the docs on Discord's snowflake, I had no idea they encoded so much data in their ids. I like all the suggestions so far from both you and @s-aring!

I'll update the proposal at the top, though I'm feeling like just an issue maybe isn't the best way for us to collaborate on this, since I think only I can edit the issue content?

Should we start a wiki?

**Comment by ericlevicky** [comment]
> Should we start a wiki?

You could make it part of the repo?  Maybe a docs folder with a md file for this proposal?  Then just open a pull request with that and update as needed?

**Comment by brebory** [comment]
Looks like J had the same idea, and created the wiki for this project: https://github.com/jartis/accountabilibot/wiki

It's technically a separate git repo, but I think it's a good place for us to store our design work. Pretty sure it supports markdown too.

I'll work on getting this ported over to the wiki later today and will close this issue when it's done.

**Comment by brebory** [comment]
Moved this document to the wiki: https://github.com/jartis/accountabilibot/wiki/System-Architecture

If you want to contribute, you just use `git clone https://github.com/jartis/accountabilibot.wiki.git` - or alternatively, when #2  gets merged, you just go into the `accountabilibot.wiki` submodule, make changes, and commit and push to master there.

From what I can tell, there's not a way to directly use PRs to manage changes to the wiki, but I DID see the following guide with suggestions on how to set it up: https://coderwall.com/p/bwpwwg/the-wiki-as-submodule-pattern

Essentially, we would make a new separate repo for the wiki so we would get PRs and other GitHub features, and then set up CI actions (probably using GitHub Actions, the guide uses CircleCI, but I think we can do everything from within GitHub Actions instead) to push changes from the new repo's main branch into acountabilibot.wiki, so the wiki for this repo stays in sync.

Closing this issue, since we can now collaborate in the Wiki.
